CREATE TABLE product
(
    id               BIGINT PRIMARY KEY AUTO_INCREMENT,
    name             VARCHAR(20) NOT NULL,
    category         VARCHAR(50) NOT NULL,
    price            BIGINT NOT NULL,
    description      VARCHAR(500) DEFAULT NULL,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)